"""crate all table

Revision ID: 97707e4b4d6b
Revises: 
Create Date: 2024-10-08 14:19:05.408336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97707e4b4d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=100), nullable=False),
    sa.Column('phone_path', sa.String(length=100), nullable=True),
    sa.Column('resource_path', sa.String(length=13), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.String(length=255), nullable=True),
    sa.Column('object_list', sa.JSON(), nullable=True),
    sa.Column('text_list', sa.String(length=10000), nullable=True),
    sa.Column('face_list', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('users')
    # ### end Alembic commands ###
