"""create images tables

Revision ID: a3a89f0024d4
Revises: 011f66be9098
Create Date: 2024-09-10 15:34:36.644437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3a89f0024d4'
down_revision: Union[str, None] = '011f66be9098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'phone_path',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.alter_column('images', 'phone_path',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
