"""add field detection to image

Revision ID: fd94159f8235
Revises: a3a89f0024d4
Create Date: 2024-09-23 10:07:57.480537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd94159f8235'
down_revision: Union[str, None] = 'a3a89f0024d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('object', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('text', sa.String(), nullable=True))
    op.add_column('images', sa.Column('face', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'face')
    op.drop_column('images', 'text')
    op.drop_column('images', 'object')
    # ### end Alembic commands ###
