FROM mysql:8.4.2

#ADD ./mysql-init-files /docker-entrypoint-initdb.d
#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && chown -R mysql:root /var/lib/mysql/

COPY ./dokcer/mysql/my.cnf /etc/mysql/conf.d/my.cnf
COPY ./docker/mysql/docker-entrypoint-initdb.d/script.sh /docker-entrypoint-initdb.d/script.sh

ARG MYSQL_DATABASE=photo_app
ENV MYSQL_DATABASE ${MYSQL_DATABASE}

ARG MYSQL_ROOT_USERNAME=root
ENV MYSQL_ROOT_USERNAME ${MYSQL_ROOT_USERNAME}

ARG MYSQL_ROOT_PASSWORD=root
ENV MYSQL_ROOT_PASSWORD  ${MYSQL_ROOT_PASSWORD}

ENTRYPOINT ["docker-entrypoint.sh"]

RUN chmod 0444 /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]

EXPOSE 3306

